# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  rabbitmq_host: '192.168.2.234'
  rabbitmq_port:  5672
  rabbitmq_user: 'guest'
  rabbitmq_password: 'guest'
  kernel.logs_dir: /var/log/apache2

  yandex_translate :
    api_key: 'trnsl.1.1.20190709T171833Z.e8988a89366fd591.4e0b091f24976313d69e25ab97d7b1182803e77c'
    url : 'https://translate.yandex.net/api/v1.5/tr.json/translate'
