old_sound_rabbit_mq:
  connections:
    default:
      host:     "%rabbitmq_host%"
      port:     "%rabbitmq_port%"
      user:     "%rabbitmq_user%"
      password: "%rabbitmq_password%"
      vhost:    '/'
      lazy:     false
      connection_timeout: 3
      read_write_timeout: 3
      keepalive: false
      heartbeat: 0
      use_socket: true

  producers:
    product:
      connection:       default
      exchange_options: { name: 'product', type: direct }

  consumers:
    product:
      connection:       default
      exchange_options: { name: 'product', type: direct }
      queue_options:    { name: 'product' }
      callback:         app.consumer.product